DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  -- cookie VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  character VARCHAR(255),
  spotify_url VARCHAR(255),
  spotify_id VARCHAR(255)
);